### ISSUE TITLE
Module Not found 'pages/giftshop/giftshop.module.scss'React TS CSS

### ISSUE THREAD

**Issue by danielkoller** [Viijay-Kr/react-ts-css#109]
**Describe the bug**
Every styles import throws an error. It says that the module is not found although it is there and the styling is applied. The settings of your extension are default. 

**To Reproduce**
As soon as a file is opened, the import shows an error. Running yarn, restarting the server or reloading the developer window doesn't help. 

**Expected behavior**
There should not be an error, because the file is there. 

**Screenshots**
![Bildschirmfoto 2023-09-25 um 11 14 30](https://github.com/Viijay-Kr/react-ts-css/assets/15102417/6a11148e-d914-4811-bf87-34107ffdc645)
![Bildschirmfoto 2023-09-25 um 11 14 52](https://github.com/Viijay-Kr/react-ts-css/assets/15102417/bfdda09c-4f55-499d-a421-1ec48e78c46f)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5.2

**Additional context**
Running the latest version of React CSS Modules and played around with older versions - didn't help unfortunately. Thanks for the great extension nonetheless!

**Comment by Viijay-Kr** [comment]
@danielkoller Thanks for reporting this issue. I apologise for the frustration. This issue could have been a regression since #97 went live. Until I find time to fix this one you could toggle the diagnostics setting off to help you from these annoying red markers

**Comment by danielkoller** [comment]
@Viijay-Kr thank you for your reply and the great plugin. I will toggle the diagnostics off for now.

**Comment by Viijay-Kr** [comment]
@danielkoller by any change do you use jsconfig path aliases ? if so can you share it with me ?

**Comment by danielkoller** [comment]
Hi @Viijay-Kr, I do. Here you go ->

"paths": {
      "@/components/*": [
        "src/components/*"
      ]
    }

**Comment by Viijay-Kr** [comment]
@danielkoller This should be fixed with the latest version of the extension. Do let me know if you find any issues

**Comment by danielkoller** [comment]
@Viijay-Kr no issues, thanks for the great work and fast fix. :)

**Comment by logone72** [comment]
@Viijay-Kr
`version: v3.2.5`
I am still experiencing the same issue. It occurs when importing through the path alias.

<img width="714" alt="image" src="https://github.com/user-attachments/assets/a8937adb-9db8-42b1-bbe3-384c9d66f4b5" />

following is my `jsconfig.json`.
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "@src/*": ["."],
      "@pages/*": ["pages/*"],
      "@common/*": ["common/*"],
      "@comComponents/*": ["common/components/*"],
      "@service/*": ["service/*"],
      "@model/*": ["model/*"],
      "@commonComponents/*": ["pages/common/*"]
    }
  },
  "include": ["src"]
}
```

Your extension would be fantastic if it could resolve this issue.

**Comment by Viijay-Kr** [comment]
@logone72 can you also provide me the path of the file where you see this error ?

**Comment by Viijay-Kr** [comment]
@logone72 can you try updating v3.2.6 and see if the issue is fixed for you ?

**Comment by Maki-Db** [comment]
This is my jsconfig.json.

```js
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["cypress", "@testing-library/cypress"]
  },
  "exclude": ["node_modules", "dist"]
}
```


I'm getting the same error, "module not found". Changing @ to src resolves the problem. I'm on version 3.2.7.

**Comment by NoelAbrahams** [comment]
I'm getting the same error for an import from the same folder:

<img width="329" height="26" alt="Image" src="https://github.com/user-attachments/assets/f2cbc2cb-c568-4bf8-8ee0-8e89f5cf3e1a" />

As stated, everything works, but there is a red underline. The file exists.

Also, sometimes the error goes away, so it is intermittent.

This is basically preventing us from using your extension as it is difficult to ignore a red error in every file.

**Comment by NoelAbrahams** [comment]
Turning off diagnostics doesn't help either.

What's the point in starting off a project and then promptly abandoning it?
